#!/bin/bash
# REV00: Wed Jan 31 18:17:10 WIB 2018
# START: Tue Jan 30 19:50:17 WIB 2018

# R: Just run "bash a01-README"

# Copyright (C) 2018 Rahmat M. Samik-Ibrahim
# http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

XX="xx"
HEAD="a"

clear
echo ""; echo "For README, just run: \"bash $0\""
echo "Is this screen size at least \"80 x 23\" characters?"
echo "RESIZE the screen if this following message does not fit in \"80 x 23\""
echo ""; echo "*** Hit Enter Key ***";
[ "$1" = "$XX" ] || (read YY)

cat - << NNNN
01 START START START START START START START START START START START START START
12345678911234567892123456789312345678941234567895123456789612345678971234567898
         10        20        30        40        50        60        70       79

12345678911234567892123456789312345678941234567895123456789612345678971234567898

         10        20        30        40        50        60        70       79
12345678911234567892123456789312345678941234567895123456789612345678971234567898
09 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXX                           TEST FOR 80 x 23                           XXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
12345678911234567892123456789312345678941234567895123456789612345678971234567898
         10        20        30        40        50        60        70       79

         10        20        30        40        50        60        70       79
12345678911234567892123456789312345678941234567895123456789612345678971234567898
19 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

         10        20        30        40        50        60        70       79
12345678911234567892123456789312345678941234567895123456789612345678971234567898
23 END                                     =====    H I T   R E T U R N    =====
NNNN

[ "$1" = "$XX" ] || (read YY)
echo ""; echo "Directory listing (running \"ls -AF\"):"
echo "================================================================================"
ls -AF
echo "================================================================================"

[ "$1" = "$XX" ] || (read YY)

cat - << NNNN
================================================================================
This is a README file for this demo.

Rahmat M. Samik-Ibrahim
================================================================================
NNNN

[ "$1" = "$XX" ] || (read YY)

PREFIX="^#.R:"

echo ""; echo "[LISTING THE] # R: LINES ===================="
for II in ${HEAD}* ; do
   RESULT=`grep $PREFIX $II`
   if [[ $RESULT ]] ; then
      printf "[%10s]: %s\n" "`cut -c 1-10 <<< $II`" "$RESULT"
   fi
done

exit

