#!/bin/bash
# REV03: Mon Sep 11 14:07:27 WIB 2017
# START: Mon Sep  5 14:25:10 WIB 2016

# Finding "EXISTS"

# Copyright (C) 2016-2017 http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


echo "File list:"
echo "=========="

for file in `ls a[01]*`
do
   echo -n $file
   if grep -q EXIST $file
      then
      echo -n " YES *******"
   fi
   echo ""
	
done

exit 0
