#!/bin/bash
# REV04: Mon Sep 11 10:39:43 WIB 2017
# START: Mon Sep  5 14:28:02 WIB 2016

# 

# Copyright (C) 2016-2017 Rahmat M. Samik-Ibrahim
# http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

TMPFILE=".thisfile.txt"
/bin/rm -f $TMPFILE
sleep 1

# ############################################
echo "APPENDING: into $TMPFILE =============="
for ii in f1 f2 
do
   echo "Appending: $ii"
   echo -n "$ii " >> $TMPFILE
done
# ############################################
for ii in f3 f4 f5 f6
do
   echo "Appending: $ii"
   echo "$ii " >> $TMPFILE
done
sleep 1

# #################################################
echo "============================================"
echo "FILE: $TMPFILE"
cat $TMPFILE

# #################################################
echo "============================================"
echo "Displaying word by word of $TMPFILE ==="
JJ=0
for ii in `cat $TMPFILE`
do
   JJ=$((JJ + 1))
   echo "V$JJ: $ii"
done

exit 0

