#!/bin/bash
# REV03: Mon Sep 11 14:27:10 WIB 2017
# START: Mon Sep  5 14:38:26 WIB 2016

# 

# Copyright (C) 2016-2017 http://RahmatM.Samik-Ibrahim.vLSM.org/
# This program is free script/software. This program is distributed in the hope 
# that it will be useful, but WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

for II in .TESTFROM .TESTTO a01-sort-script a02-some-command-lines
do
   echo "================================"
   [ -f $II ] && echo "[$II] is a file"
   [ -f $II ] || echo "[$II] is NOT a file"

   if [ -d $II ] 
      then echo "[$II] is a directory"
   else 
      echo "[$II] is NOT a directory"
   fi
done
echo "================================"

exit

